### ISSUE TITLE
Consider using prisma instead of typeorm

### ISSUE THREAD

**Issue by dmtrKovalenko** [saltyshiomix/ark#5]
As from my perspective, it is much more useful in the case of typescript. 
Moreover, it is `v2` coming that will make usage even simpler.

**Comment by saltyshiomix** [comment]
Hi @dmtrKovalenko !

Ok, I'll investigate it :)

**Comment by saltyshiomix** [comment]
Oh, super duper interesting!
Thank you for your letting me know 👍

**Comment by saltyshiomix** [comment]
I decided to use TypeOrm until prisma v2 released, so I closed this issue for now.
