### ISSUE TITLE
Consider using PostGraphile instead of typeorm :)

### ISSUE THREAD

**Issue by wisekaa03** [saltyshiomix/ark#7]
Postgraphile is much faster than Prisma.

See this:
https://www.graphile.org/postgraphile/usage-library/
https://www.graphile.org/postgraphile/postgresql-schema-design/

**Comment by saltyshiomix** [comment]
I'll search both of them later next week :)

**Comment by saltyshiomix** [comment]
I decided to use TypeOrm because ARK is a sample repo for authentication, not for speed.
